name: buddy_engine
description: Buddy Voice AI Engine
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_onnxruntime: ^1.7.0
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.0